In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_202103 = pd.read_csv('../data/raw/202103_통신카드CB결합.csv')
df_202103.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202103,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,-1,0,0
1,202103,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
2,202103,SYN_2,1,30,420,11,11.0,0,0,0,...,0,-1,0,0,1,0,0,0,0,0
3,202103,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202103,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,1,0,1,0,0,0

In [3]:
df_202103.to_parquet('../data/raw/202103_통신카드CB결합.parquet')

In [4]:
df_202103 = pd.read_parquet('../data/raw/202103_통신카드CB결합.parquet')

In [6]:
df_202103.info()

<class 'pandas.DataFrame'>
RangeIndex: 330000 entries, 0 to 329999
Columns: 738 entries, BASE_YM to YOY_R3M_ITRT_COMM_MESSENGER_CS
dtypes: float64(369), int64(363), str(6)
memory usage: 1.8 GB

In [3]:
df_202106 = pd.read_csv('../data/raw/202106_통신카드CB결합.csv')
df_202106.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202106,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,0,0,0
1,202106,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,202106,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,202106,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202106,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [21]:
df_202109 = pd.read_csv('../data/raw/202109_통신카드CB결합.csv')
df_202109.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202109,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,0,0,0
1,202109,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,202109,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,202109,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202109,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df_202112 = pd.read_csv('../data/raw/202112_통신카드CB결합.csv')
df_202112.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_WEBTOON_CS,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS
0,202112,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,0,-1,0,0,0,0,0,0
1,202112,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,202112,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,202112,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,202112,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df_202203 = pd.read_csv('')

In [4]:
df_schema = pd.read_excel('../data/raw/093-117_금융 합성데이터_데이터구성상세.xlsx', sheet_name='11.통신카드CB 결합정보')
df_schema

      No                             필드명                     설명 코드여부    타입
0      1                         BASE_YM                   기준년월    N  Char
1      2                         CUST_ID                  고객식별자    N  Char
2      3                             SEX                     성별    Y  Char
3      4                             AGE                    연령대    Y  Char
4      5                           JB_TP                    직업군    Y  Char
..   ...                             ...                    ...  ...   ...
733  734     YOY_R3M_ITRT_INFO_PORTAL_CS    전년동기대비_정보_포탈_관심도_변화    Y  Char
734  735        YOY_R3M_ITRT_COMM_SNS_CS   전년동기대비_커뮤_SNS_관심도_변화    Y  Char
735  736       YOY_R3M_ITRT_COMM_VOIP_CS  전년동기대비_커뮤_VoIP_관심도_변화    Y  Char
736  737       YOY_R3M_ITRT_COMM_DATE_CS   전년동기대비_커뮤_데이트_관심도_변화    Y  Char
737  738  YOY_R3M_ITRT_COMM_MESSENGER_CS   전년동기대비_커뮤_메신저_관심도_변화    Y  Char

[738 rows x 5 columns]

In [ ]:
import pandas as pd
import gc

def find_special_patterns(df12, df9, df6, df3, id_col='CUST_ID'):

    print("데이터 인덱스 정렬 및 교집합 추출")
    
    idx12 = df12.set_index(id_col)
    idx9 = df9.set_index(id_col)
    idx6 = df6.set_index(id_col)
    idx3 = df3.set_index(id_col)

    common_ids = idx12.index.intersection(idx9.index).intersection(idx6.index).intersection(idx3.index)
    common_cols = idx12.columns.intersection(idx9.columns).intersection(idx6.columns).intersection(idx3.columns)

    m12 = idx12.loc[common_ids, common_cols]
    m9 = idx9.loc[common_ids, common_cols]
    m6 = idx6.loc[common_ids, common_cols]
    m3 = idx3.loc[common_ids, common_cols]

    print(f"✅ 매칭 완료: {len(common_ids)}명 / 검사 대상: {len(common_cols)}개 컬럼\n")

    def check_same(past, recent):
        return (past == recent) | (past.isna() & recent.isna())

    is_all_same = check_same(m12, m9) & check_same(m9, m6) & check_same(m6, m3)
    static_mask = is_all_same.all()
    static_columns = static_mask[static_mask].index.tolist()
    
    num_cols = m12.select_dtypes(include='number').columns
    n12, n9, n6, n3 = m12[num_cols], m9[num_cols], m6[num_cols], m3[num_cols]

    is_increasing = (n12 <= n9) & (n9 <= n6) & (n6 <= n3)
    inc_mask = is_increasing.all()
    
    increasing_columns = [col for col in inc_mask[inc_mask].index.tolist() if col not in static_columns]

    print(f"미변화 컬럼: {len(static_columns)}개")
    print(f"누적/증가 컬럼: {len(increasing_columns)}개")

    del idx12, idx9, idx6, idx3, m12, m9, m6, m3
    del is_all_same, n12, n9, n6, n3, is_increasing
    gc.collect()

    return {
        'static': static_columns,
        'increasing': increasing_columns
    }

result = find_special_patterns(df_202103, df_202106, df_202109, df_202112)
print("안 변하는 변수들:", result['static'])
print("증가만 하는 변수들:", result['increasing'])

⏳ 데이터 인덱스 정렬 및 교집합 추출 중...
✅ 매칭 완료: 330000명 / 검사 대상: 737개 컬럼

🗑️ 1. 변화가 전혀 없는 컬럼 (Static): 207개
📈 2. 누적/증가만 하는 컬럼 (Increasing): 1개
안 변하는 변수들: ['SEX', 'AGE', 'JB_TP', 'HOME_ADM', 'COM_ADM', 'HIGHEND_CD1', 'HIGHEND_CD2', 'HIGHEND_CD3', 'HIGHEND_CD4', 'LIF_STG', 'HB_1ST', 'COFFEE_1ST', 'BUY_LUX_YN', 'APP_GD', 'MUSIC_GD', 'GAME_GD', 'GOLF_GD', 'PET_GD', 'DONATION_YN', 'TRAVEL_GD', 'CAR_YN', 'VIP_CARD_YN', 'CHILD_EDU', 'RET_SIL', 'TRAVEL_OS', 'TRAVEL_JJ', 'GOLF_INDOOR', 'PREFER_SPORTS', 'PREFER_HIK', 'RNCAR_JJ_YN', 'BUY_PHONE_YN', 'AIRLINE_OS_YN', 'T_AGENCY_OS_YN', 'KTX_YN', 'MUSEUM_YN', 'BASEBALL_YN', 'PYE_ICM', 'PYE_ICM_RT', 'PYE_ALL_CD_USE_AMT', 'PYE_NET_ASST', 'PYE_CAR_OWN', 'PYE_CAR_LN_AMT', 'PYE_CAR_SIZE', 'PYE_FAM_CNT', 'PYE_ELE_CAR_YN', 'PYE_HOME_CHAR_DIST', 'PYE_COM_CHAR_DIST', 'HOUS_LN_BAL_NEW', 'BUY_HOUS_PRICE', 'PYE_MAX_DLQ_DAY', 'PYE_C1M2B4W03', 'PYE_C1M2B5W03', 'PYE_C1M210000', 'PYE_C18233003', 'PYE_C18233004', 'PYE_C18233005', 'PYE_C1L120012', 'PYE_C1L120161', 'PYE_C1L120196', 'PYE_C1L120237', 'PYE_C1L120250', 'PYE_L10210000', 'PYE_L1021003P', 'PYE_L1021006P', 'PYE_L102100CP', 'PYE_L90210100', 'PYE_L90210200', 'PYE_L90210300', 'PYE_L10210800', 'PYE_L10210B00', 'PYE_L10216000', 'PYE_L90216100', 'PYE_L90216300', 'PYE_L10216800', 'PYE_L10216B00', 'PYE_L1021A000', 'PYE_L10231000', 'PYE_D10110001', 'PYE_D10110003', 'PYE_D10110006', 'PYE_D1011000C', 'PYE_D10210D00', 'PYE_D10232000', 'PYE_AL012G005', 'PYE_AL012G011', 'PYE_AL012G019', 'PYE_SC0000000', 'B1Y_EQP_MDL', 'R3M_CAR_AMT', 'R3M_TRAVEL_OS_AMT', 'R3M_E_CHARGE_AMT', 'R3M_M_OUTLET_AMT', 'R3M_M_DF_AMT', 'R3M_M_DEP_G_AMT', 'R3M_M_DEP_A_AMT', 'R3M_M_DEP_I_AMT', 'R3M_M_MART_V_AMT', 'PYE_CCIR', 'B1Y_MOB_OS', 'YOY_HIGHEND_CD1_CHYN', 'YOY_HIGHEND_CD2_CHYN', 'YOY_HIGHEND_CD3_CHYN', 'YOY_HIGHEND_CD4_CHYN', 'R6M_CAR_AMT', 'R6M_TRAVEL_OS_AMT', 'R6M_E_CHARGE_AMT', 'R6M_M_OUTLET_AMT', 'R6M_M_DF_AMT', 'R6M_M_DEP_G_AMT', 'R6M_M_DEP_A_AMT', 'R6M_M_DEP_I_AMT', 'R6M_M_MART_V_AMT', 'R9M_CAR_AMT', 'R9M_TRAVEL_OS_AMT', 'R9M_E_CHARGE_AMT', 'R9M_M_OUTLET_AMT', 'R9M_M_DF_AMT', 'R9M_M_DEP_G_AMT', 'R9M_M_DEP_A_AMT', 'R9M_M_DEP_I_AMT', 'R9M_M_MART_V_AMT', 'R9M_MBR_USE_CNT', 'R9M_OUTSIDE_WDAY_CNT', 'R9M_OUTSIDE_HDAY_CNT', 'R9M_HOME_WDAY_STAY_TIME', 'R9M_MOV_WDAY_DIST', 'R12M_CAR_AMT', 'R12M_TRAVEL_OS_AMT', 'R12M_E_CHARGE_AMT', 'R12M_M_OUTLET_AMT', 'R12M_M_DF_AMT', 'R12M_M_DEP_G_AMT', 'R12M_M_DEP_A_AMT', 'R12M_M_DEP_I_AMT', 'R12M_M_MART_V_AMT', 'R12M_MBR_USE_CNT', 'R12M_OUTSIDE_WDAY_CNT', 'R12M_OUTSIDE_HDAY_CNT', 'R12M_HOME_WDAY_STAY_TIME', 'R12M_MOV_WDAY_DIST', 'CPYT_CAR_AMT_RT', 'CPYT_TRAVEL_OS_AMT_RT', 'CPYT_E_CHARGE_AMT_RT', 'CPYT_M_OUTLET_AMT_RT', 'CPYT_M_DF_AMT_RT', 'CPYT_M_DEP_G_AMT_RT', 'CPYT_M_DEP_A_AMT_RT', 'CPYT_M_DEP_I_AMT_RT', 'CPYT_M_MART_V_AMT_RT', 'CPYT_MBR_USE_CNT_RT', 'CPYT_CAR_CUM_AMT_RT', 'CPYT_TRAVEL_OS_CUM_AMT_RT', 'CPYT_E_CHARGE_CUM_AMT_RT', 'CPYT_M_OUTLET_CUM_AMT_RT', 'CPYT_M_DF_CUM_AMT_RT', 'CPYT_M_DEP_G_CUM_AMT_RT', 'CPYT_M_DEP_A_CUM_AMT_RT', 'CPYT_M_DEP_I_CUM_AMT_RT', 'CPYT_M_MART_V_CUM_AMT_RT', 'CPYT_MBR_USE_CUM_CNT_RT', 'CPYT_CAR_CPPY_AMT_RT', 'CPYT_TRAVEL_OS_CPPY_AMT_RT', 'CPYT_E_CHARGE_CPPY_AMT_RT', 'CPYT_M_OUTLET_CPPY_AMT_RT', 'CPYT_M_DF_CPPY_AMT_RT', 'CPYT_M_DEP_G_CPPY_AMT_RT', 'CPYT_M_DEP_A_CPPY_AMT_RT', 'CPYT_M_DEP_I_CPPY_AMT_RT', 'CPYT_M_MART_V_CPPY_AMT_RT', 'CPYT_MBR_USE_CPPY_CNT_RT', 'CPYT_CAR_CPPY_CUM_AMT_RT', 'CPYT_TRAVEL_OS_CPPY_CUM_AMT_RT', 'CPYT_E_CHARGE_CPPY_CUM_AMT_RT', 'CPYT_M_OUTLET_CPPY_CUM_AMT_RT', 'CPYT_M_DF_CPPY_CUM_AMT_RT', 'CPYT_M_DEP_G_CPPY_CUM_AMT_RT', 'CPYT_M_DEP_A_CPPY_CUM_AMT_RT', 'CPYT_M_DEP_I_CPPY_CUM_AMT_RT', 'CPYT_M_MART_V_CPPY_CUM_AMT_RT', 'CPYT_MBR_USE_CPPY_CUM_CNT_RT', 'QOQ_HOUS_LN_BAL_NEW_CHYN', 'QOQ_BUY_HOUS_PRICE_CHYN', 'QOQ_R3M_CAR_AMT_RTC', 'QOQ_R3M_TRAVEL_OS_AMT_RTC', 'QOQ_R3M_E_CHARGE_AMT_RTC', 'QOQ_R3M_M_OUTLET_AMT_RTC', 'QOQ_R3M_M_DF_AMT_RTC', 'QOQ_R3M_M_DEP_G_AMT_RTC', 'QOQ_R3M_M_DEP_A_AMT_RTC', 'QOQ_R3M_M_DEP_I_AMT_RTC', 'QOQ_R3M_M_MART_V_AMT_RTC', 'YOY_HOUS_LN_BAL_NEW_CHYN', 'YOY_BUY_HOUS_PRICE_CHYN', 'YOY_R3M_CAR_AMT_RTC', 'YOY_R3M_TRAVEL_OS_AMT_RTC', 'YOY_R3M_E_CHARGE_AMT_RTC', 'YOY_R3M_M_OUTLET_AMT_RTC', 'YOY_R3M_M_DF_AMT_RTC', 'YOY_R3M_M_DEP_G_AMT_RTC', 'YOY_R3M_M_DEP_A_AMT_RTC', 'YOY_R3M_M_DEP_I_AMT_RTC', 'YOY_R3M_M_MART_V_AMT_RTC', 'YOY_R3M_MBR_USE_CNT_RTC', 'YOY_R3M_OUTSIDE_WDAY_CNT_RTC', 'YOY_R3M_OUTSIDE_HDAY_CNT_RTC', 'YOY_R3M_HOME_WDAY_STAY_TIME_RTC', 'YOY_R3M_MOV_WDAY_DIST_RTC']
증가만 하는 변수들: ['BASE_YM']

- 최장연체일수_미해제_전년말기준 변수는 모든 분기 데이터 셋에서 동일하게 기록되어 있음

# 1. 가이드

In [2]:
df_202112 = pd.read_csv('../data/raw/202112_통신카드CB결합.csv')
df_202203 = pd.read_csv('../data/raw/202203_통신카드CB결합.csv')

- PYE_MAX_DLQ_DAY : 최장연체일수_미해제_전년말기준

-> 22년 1년동안의 최장연체일수를 기록한 칼럼

-> 롤레이트 분석시 활용해야 하지만, 우리 데이터에는 롤레이트 분석이 불가능(기준시점 + 1개월이라는 수치를 계산할 수 없음)

In [3]:
df_202112 = df_202112.merge(df_202203[['CUST_ID','PYE_MAX_DLQ_DAY']], how = 'inner', on = 'CUST_ID')
df_202112.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS,PYE_MAX_DLQ_DAY_y
0,202112,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,-1,0,0,0,0,0,0,0.0
1,202112,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,202112,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,202112,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
4,202112,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [15]:
# 최장연체일수_미해제_90일 이상은 22년도 1월에 이미 연체 고객 -> 대출 불가능
df_2021 = df_202112[df_202112['PYE_MAX_DLQ_DAY_x'] <= 90]
df_2021.head()

,BASE_YM,CUST_ID,SEX,AGE,JB_TP,HOME_ADM,COM_ADM,HIGHEND_CD1,HIGHEND_CD2,HIGHEND_CD3,...,YOY_R3M_ITRT_ENT_MUSIC_CS,YOY_R3M_ITRT_INFO_NEWS_CS,YOY_R3M_ITRT_INFO_BOOK_CS,YOY_R3M_ITRT_INFO_BLOG_CS,YOY_R3M_ITRT_INFO_PORTAL_CS,YOY_R3M_ITRT_COMM_SNS_CS,YOY_R3M_ITRT_COMM_VOIP_CS,YOY_R3M_ITRT_COMM_DATE_CS,YOY_R3M_ITRT_COMM_MESSENGER_CS,PYE_MAX_DLQ_DAY_y
0,202112,SYN_0,2,35,420,42,42.0,0,0,0,...,0,0,-1,0,0,0,0,0,0,0.0
1,202112,SYN_1,2,50,910,41,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
2,202112,SYN_2,1,30,420,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
3,202112,SYN_3,1,25,910,11,11.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
4,202112,SYN_4,2,40,420,47,47.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [26]:
df_tmp = df_202112[df_202112['PYE_MAX_DLQ_DAY_x'] <= 90]['PYE_MAX_DLQ_DAY_y'].value_counts().reset_index()
df_tmp

     PYE_MAX_DLQ_DAY_y   count
0                  0.0  328516
1                 12.0     320
2                  8.0     113
3                 13.0      52
4                 11.0      19
..                 ...     ...
109              716.0       1
110              103.0       1
111              451.0       1
112              252.0       1
113              440.0       1

[114 rows x 2 columns]

7건이긴 하지만, 논리 자체에 맞지 않는 값

-> 20년도 12월 31일에 90일 이하로 연체를 진행 + 21년도 12월 31일 전체가 연체여도 455일을 넘으면 안 됨.

In [32]:
sum(df_tmp['PYE_MAX_DLQ_DAY_y'] > 365 + 90)

7

- 21년도의 데이터로 1년을 관찰기간으로 잡는다고 가정해도, 22년도 이후의 성과예측에 대한 연체 정보가 없음
- 관찰기간을 6개월로 잡아도, 7~9월 사이의 연체는 식별할 수 없음(21/12/31에 연체된 사람들의 기록만 존재)